import {
  Playfair_Display,
  Inter,
  Dynalight,
  Bebas_Neue,
} from 'next/font/google';
import './globals.css';

const playFair = Playfair_Display({
  variable: '--font-playfair',
  weight: '400',
  subsets: ['latin'],
});

const inter = Inter({
  weight: '400',
  variable: '--font-inter',
  subsets: ['latin'],
});

const dynalight = Dynalight({
  variable: '--font-dynalight',
  weight: '400',
  subsets: ['latin'],
});

const bebas = Bebas_Neue({
  variable: '--font-bebas',
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Nobel Joseph House',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${dynalight.variable} 
          ${bebas.variable}
          ${inter.variable} 
          ${playFair.variable} 
          `}
      >
        {children}
      </body>
    </html>
  );
}
